# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appremotesettings', '0002_strict_datatypes_for_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='desc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='desc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='key',
            name='desc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='key',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='key',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
