# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appremotesettings', '0003_char_not_text_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='desc',
            field=models.CharField(max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='desc',
            field=models.CharField(max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='key',
            name='datatype',
            field=models.IntegerField(choices=[(1, 'Boolean'), (2, 'Integer'), (3, 'Float'), (4, 'String')], default=1, verbose_name='data type'),
        ),
        migrations.AlterField(
            model_name='key',
            name='desc',
            field=models.CharField(max_length=255, verbose_name='description'),
        ),
    ]
