# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appremotesettings', '0005_add_date_datatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='desc',
            field=models.CharField(blank=True, max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='desc',
            field=models.CharField(blank=True, max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='key',
            name='desc',
            field=models.CharField(blank=True, max_length=255, verbose_name='description'),
        ),
    ]
