# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appremotesettings', '0006_optional_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifier',
            name='value',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
